Generic method to get attribute values from LDAP
ltb-project/ltb-common pull request #32
Opened 2024-08-26 13:09 UTC by abpai94

2024-08-26 13:20 UTC, coudot requested changes

2024-08-26 13:20 UTC, coudot commented on phpunit.xml
> +<phpunit xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" colors="true" xsi:noNamespaceSchemaLocation="https://schema.phpunit.de/11.0/phpunit.xsd">  xmlns:xsi="http://www.w3.org/2001/XMLSchema-i
Please remove this change

2024-08-26 13:20 UTC, coudot commented on src/Ltb/Ldap.php
> +    function get_attribute_value($dn, $attribute) {
It would be better to call it `get_attribute_values`

2024-08-26 14:27 UTC, coudot commented on phpunit.xml
> +<phpunit xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" colors="true" xsi:noNamespaceSchemaLocation="https://schema.phpunit.de/11.0/phpunit.xsd">  xmlns:xsi="http://www.w3.org/2001/XMLSchema-i
```suggestion
<phpunit xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" colors="true" xsi:noNamespaceSchemaLocation="https://schema.phpunit.de/11.0/phpunit.xsd">
```

2024-08-26 14:39 UTC, coudot approved these changes

2024-08-26 14:43 UTC, coudot commented
We should also add a unit test in tests/Ltb/LdapTest.php

2024-08-26 17:31 UTC, davidcoutadeur commented
I'll give a look to this feature on tomorrow.

@abpai94 : if the feature is finished, could your 1/ squash your commits and 2/ rebase on top of master? Thanks

2024-08-27 08:40 UTC, davidcoutadeur requested changes
Ok for me.

Last thing: we need to add the unit test for the new get_attribute_values function.

You can give a look to function test_get_password_value in file tests/Ltb/LdapTest.php

2024-09-18 13:23 UTC, abpai94 commented
@davidcoutadeur tests added, ready to merge!

2024-09-18 15:26 UTC, davidcoutadeur approved these changes

2024-09-18 15:26 UTC, merged